CREATE DATABASE rushBanana_Db;

CREATE USER rushBanana_User WITH PASSWORD 'strong_password';

GRANT CONNECT ON DATABASE rushBanana_Db TO rushBanana_User;

GRANT USAGE ON SCHEMA public TO rushBanana_User;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO rushBanana_User;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO rushBanana_User;