
# Key бота
botToken: 8195690396:AAHxkOmCu513fNQKjUZLdxLBesKr-mYy-fM

# Уровень логгера
log-level: 5

# Это прод?
production: false

# Список админов
admins:
  - !!str Sazonovme

# БД конфиг
user_db: rushbanana_user
passwordUser_db: secret_password
name_db: rushbanana_db
port_db: 5432